using AutomationFramework.Model.Database.NFL;

namespace AutomationFramework.DefaultRequests
{
    internal static class SimulationFixtureRatingsRequests
    {
        private static SimulationFixtureRatingsModel GetSimulationFixtureRatingRequest(string fixtureKey,
            string playerId, string name, string position, string team, string statType, string dob, string starter, DateTime timestamp)
        {
            var request = new SimulationFixtureRatingsModel()
            {
                FixtureKey = fixtureKey,
                Key = "Production",
                GameState = "PM",
                PlayerID = playerId,
                Name = name,
                Team = team,
                Position = position,
                StatType = statType,
                DOB = dob,
                Starter = starter,
                Timestamp = timestamp
            };

            return request;
        }

        public static SimulationFixtureRatingsModel GetSimulationFixtureRatingCoachRequest(string fixtureKey,
            string playerId, string name, string position, string team, string statType, string dob, string starter, string onField, DateTime timestamp)
        {
            var request = GetSimulationFixtureRatingRequest(fixtureKey, playerId, name, position, team, statType, dob, starter, timestamp);

            request.OL5 = "1100.912";
            request.oFBonPlay = "875";
            request.oExtraBack = "1200";
            request.oExtraWR = "915";
            request.dExtraDB = "1067.598";
            request.dExtraLB = "1348.117";
            request.OC = "0";
            request.OG = "0";
            request.OT = "0";
            request.DEEP = "0";
            request.BOX = "0";
            request.DE = "0";
            request.ED = "0";
            request.DI = "0";
            request.Available = "0";
            request.QBonField = onField;
            request.FBonField = "0";
            request.BACKonFieldpass = "0";
            request.BACKonFieldrush = "0";
            request.TEonFieldpass = "0";
            request.TEonFieldrush = "0";
            request.WRonField = "0";
            request.OLonField = "0";
            request.DLonFieldPass = "0";
            request.DLonFieldRush = "0";
            request.LBonFieldPass = "0";
            request.LBonFieldRush = "0";
            request.DBonFieldPass = "0";
            request.DBonFieldRush = "0";
            request.KonField = "0";
            request.PonField = "0";
            request.cStrategyTwoPtProb = "1158.438";
            request.cStrategyGoForIt = "1383.72";
            request.cStrategyPunt = "0";
            request.cStrategyFieldGoal = "0";
            request.cStrategyKneel = "2064.19868646322";
            request.cStrategySpike = "0";
            request.cDeferKickOff = "1157.259";
            request.qbPace = "0";
            request.oPace = "1075.54";
            request.dPace = "1104.817";
            request.oPrePlayPenFor = "1100";
            request.oPrePlayPenAgainst = "1100";
            request.dPrePlayPenFor = "1100";
            request.dPrePlayPenAgainst = "1100";
            request.oPostPlayPenFor = "1100";
            request.oPostPlayPenAgainst = "1100";
            request.dPostPlayPenFor = "1100";
            request.dPostPlayPenAgainst = "1100";
            request.cPenaltyPreSnapOffBySelf = "1100.799";
            request.cPenaltyPreSnapDefBySelf = "1099.672";
            request.cPenaltyPreSnapOffByOpponent = "1099.201";
            request.cPenaltyPreSnapDefByOpponent = "1100.328";
            request.cPenaltyOff10PassBySelf = "1099.054";
            request.cPenaltyOff10RushBySelf = "1100.058";
            request.cPenaltyOff10PassByOpponent = "1100.946";
            request.cPenaltyOff10RushByOpponent = "1099.942";
            request.cPenaltyOff15BySelf = "1103.474";
            request.cPenaltyDef15BySelf = "1099.552";
            request.cPenaltyOff15ByOpponent = "1096.526";
            request.cPenaltyDef15ByOpponent = "1100.448";
            request.cPenaltyDef5Auto1stBySelf = "1098.219";
            request.cPenaltyDef5Auto1stByOpponent = "1101.781";
            request.rPassInterference = "0";
            request.dPassInterference = "0";
            request.oFumble = "1097.833";
            request.dFumble = "1097.038";
            request.qbRedzone = "0";
            request.oRedzone = "1104.155";
            request.dRedzone = "1095.845";
            request.qbPassing = "0";
            request.rRunning = "0";
            request.qbRushPass = "0";
            request.oRushPass = "1062.995";
            request.dRushPass = "1111.37";
            request.oRushPass1stAnd10 = "1042.959";
            request.oRushPass2ndAndShort = "1032.857";
            request.oRushPass2ndAndLong = "1128.798";
            request.oRushPass3rdAndShort = "979.948";
            request.oRushPass3rdAndLong = "1173.193";
            request.oRushPassDecisionRedZone = "1128.304";
            request.rRusherShort = "0";
            request.rRusherLong = "0";
            request.rRushing = "0";
            request.oRushing = "1106.461";
            request.dRushing = "1093.494";
            request.oRushBlock = "0";
            request.dRushDefense = "0";
            request.dTackleOrAssist = "0";
            request.qbPressure = "0";
            request.oPressure = "1116.707";
            request.dPressure = "1074.809";
            request.qbSack = "0";
            request.oSack = "1079.293";
            request.dSack = "1104.261";
            request.dSacker = "0";
            request.dPassRushRate = "0";
            request.oPassBlock = "0";
            request.dPassBlock = "0";
            request.qbScramble = "0";
            request.oScramble = "1096.056";
            request.dScramble = "1102.367";
            request.qbScrambleYards = "0";
            request.oScrambleYards = "1094.044";
            request.dScrambleYards = "1096.454";
            request.qbPassType = "0";
            request.oPassType = "1107.41";
            request.dPassType = "1057.1";
            request.qbPassFirstDownAttempt = "0";
            request.oPassFirstDownAttempt = "1109.269";
            request.dPassFirstDownAttempt = "1089.549";
            request.qbShortPassAttempt = "0";
            request.oShortPassAttempt = "1096.504";
            request.dShortPassAttempt = "1102.468";
            request.qbLongPassAttempt = "0";
            request.oLongPassAttempt = "1098.727";
            request.dLongPassAttempt = "1102.29";
            request.oReceiverAbility = "0";
            request.qbPassIntercept = "0";
            request.qbShortPassComplete = "0";
            request.oShortPassComplete = "1103.461";
            request.dShortPassComplete = "1091.609";
            request.qbMediumPassComplete = "0";
            request.oMediumPassComplete = "1119.314";
            request.dMediumPassComplete = "1085.924";
            request.qbLongPassComplete = "0";
            request.oLongPassComplete = "1117.507";
            request.dLongPassComplete = "1084.156";
            request.oShortPassIntercept = "1099.362";
            request.dShortPassIntercept = "1102.29";
            request.oMediumPassIntercept = "1100.826";
            request.dMediumPassIntercept = "1098.019";
            request.oLongPassIntercept = "1100.416";
            request.dLongPassIntercept = "1099.545";
            request.qbShortPassYAC = "0";
            request.oShortPassYAC = "1079.159";
            request.dShortPassYAC = "1125.898";
            request.qbMediumPassYAC = "0";
            request.oMediumPassYAC = "1065.37";
            request.dMediumPassYAC = "1131.103";
            request.qbLongPassYAC = "0";
            request.oLongPassYAC = "1062.077";
            request.dLongPassYAC = "1128.526";
            request.dPassCover = "0";
            request.dInterceptor = "0";
            request.rReceiverShort = "0";
            request.rReceiverMedium = "0";
            request.rReceiverLong = "0";
            request.rReceiverEndzone = "0";
            request.kFieldGoalBlock = "0";
            request.kFieldGoalMake = "0";
            request.kPunt = "1096.957";
            request.rPunt = "1100.004";
            request.kPuntReturn = "1083.374";
            request.rPuntReturn = "1127.119";
            request.kKickOffTouchback = "976.236";
            request.rKickOffTouchback = "1191.423";
            request.kKickReturnEfficiency = "1101.182";
            request.rKickReturnEfficiency = "1098.542";

            return request;
        }

        public static SimulationFixtureRatingsModel GetSimulationFixtureRatingPlayerRequest(string fixtureKey,
            string playerId, string name, string position, string team, string statType, string dob, string starter, string onField, DateTime timestamp)
        {
            var request = GetSimulationFixtureRatingRequest(fixtureKey, playerId, name, position, team, statType, dob, starter, timestamp);
            //new Random().NextInt64(100, 1200) + new Random().NextDouble().ToString("#.##");

            request.oFBonPlay = "906.014";
            request.oExtraBack = "772.213";
            request.oExtraWR = "0";
            request.dExtraDB = "0";
            request.dExtraLB = "0";
            request.OC = "0.2";
            request.OG = "0.4";
            request.OT = "0.4";
            request.DEEP = "0.01";
            request.BOX = "0.663";
            request.DE = "0.042";
            request.ED = "0.281";
            request.DI = "0.003";
            request.Available = "1";
            request.QBonField = onField;
            request.FBonField = "1100";
            request.BACKonFieldpass = "0.846";
            request.BACKonFieldrush = "0.855";
            request.TEonFieldpass = "1";
            request.TEonFieldrush = "1";
            request.WRonField = "1";
            request.OLonField = "1";
            request.DLonFieldPass = "1";
            request.DLonFieldRush = "1";
            request.LBonFieldPass = "1";
            request.LBonFieldRush = "1";
            request.DBonFieldPass = "1";
            request.DBonFieldRush = "1";
            request.KonField = "750";
            request.PonField = "750";
            request.cStrategyTwoPtProb = "0";
            request.cStrategyGoForIt = "0";
            request.cStrategyPunt = "0";
            request.cStrategyFieldGoal = "0";
            request.cStrategyKneel = "0";
            request.cStrategySpike = "0";
            request.cDeferKickOff = "0";
            request.qbPace = "1062.004";
            request.oPace = "1100";
            request.dPace = "1100";
            request.oPrePlayPenFor = "1100";
            request.oPrePlayPenAgainst = "1100";
            request.dPrePlayPenFor = "1100";
            request.dPrePlayPenAgainst = "1100";
            request.oPostPlayPenFor = "1100";
            request.oPostPlayPenAgainst = "1100";
            request.dPostPlayPenFor = "1100";
            request.dPostPlayPenAgainst = "1100";
            request.cPenaltyPreSnapOffBySelf = "0";
            request.cPenaltyPreSnapDefBySelf = "0";
            request.cPenaltyPreSnapOffByOpponent = "0";
            request.cPenaltyPreSnapDefByOpponent = "0";
            request.cPenaltyOff10PassBySelf = "0";
            request.cPenaltyOff10RushBySelf = "0";
            request.cPenaltyOff10PassByOpponent = "0";
            request.cPenaltyOff10RushByOpponent = "0";
            request.cPenaltyOff15BySelf = "0";
            request.cPenaltyDef15BySelf = "0";
            request.cPenaltyOff15ByOpponent = "0";
            request.cPenaltyDef15ByOpponent = "0";
            request.cPenaltyDef5Auto1stBySelf = "0";
            request.cPenaltyDef5Auto1stByOpponent = "0";
            request.rPassInterference = "962.966";
            request.dPassInterference = "1157.272";
            request.oFumble = "0";
            request.dFumble = "0";
            request.qbRedzone = "1102.812";
            request.oRedzone = "1097.872";
            request.dRedzone = "1104.313";
            request.qbPassing = "54.729";
            request.rRunning = "53.432";
            request.qbRushPass = "1060";
            request.oRushPass = "1100";
            request.dRushPass = "1100";
            request.oRushPass1stAnd10 = "0";
            request.oRushPass2ndAndShort = "0";
            request.oRushPass2ndAndLong = "0";
            request.oRushPass3rdAndShort = "0";
            request.oRushPass3rdAndLong = "0";
            request.oRushPassDecisionRedZone = "0";
            request.rRusherShort = "685.822";
            request.rRusherLong = "50.478";
            request.rRushing = "1109.663";
            request.oRushing = "1090.007";
            request.dRushing = "1100";
            request.oRushBlock = "48.359";
            request.dRushDefense = "55.31";
            request.dTackleOrAssist = "1108.124";
            request.qbPressure = "1073.618";
            request.oPressure = "1100" + new Random().NextDouble().ToString("#.##");
            request.dPressure = "1095.55";
            request.qbSack = "1082.861";
            request.oSack = "1101" + new Random().NextDouble().ToString("#.##");
            request.dSack = "1101" + new Random().NextDouble().ToString("#.##");
            request.dSacker = "1101.753" + new Random().NextDouble().ToString("#.##");
            request.dPassRushRate = "1101" + new Random().NextDouble().ToString("#.##");
            request.oPassBlock = "53.33";
            request.dPassBlock = "56.867";
            request.qbScramble = "964.951";
            request.oScramble = "1100.732";
            request.dScramble = "1099.782";
            request.qbScrambleYards = "1100";
            request.oScrambleYards = "1098.204";
            request.dScrambleYards = "1101.844";
            request.qbPassType = "1092" + new Random().NextDouble().ToString("#.##");
            request.oPassType = "1101.998";
            request.dPassType = "1100.365";
            request.qbPassFirstDownAttempt = "1098.142";
            request.oPassFirstDownAttempt = "1103.862";
            request.dPassFirstDownAttempt = "1096.155";
            request.qbShortPassAttempt = "1121.793";
            request.oShortPassAttempt = "1099.517";
            request.dShortPassAttempt = "1097.607";
            request.qbLongPassAttempt = "1081.255";
            request.oLongPassAttempt = "1107.286";
            request.dLongPassAttempt = "1096.188";
            request.oReceiverAbility = "57.9";
            request.qbPassIntercept = "1041.639";
            request.qbShortPassComplete = "1072.155";
            request.oShortPassComplete = "1075.056";
            request.dShortPassComplete = "0";
            request.qbMediumPassComplete = "1068.504";
            request.oMediumPassComplete = "1083.842";
            request.dMediumPassComplete = "0";
            request.qbLongPassComplete = "1091.008";
            request.oLongPassComplete = "1080.379";
            request.dLongPassComplete = "0";
            request.oShortPassIntercept = "1097.021";
            request.dShortPassIntercept = "1100";
            request.oMediumPassIntercept = "1100.088";
            request.dMediumPassIntercept = "1100";
            request.oLongPassIntercept = "1100.142";
            request.dLongPassIntercept = "1100";
            request.qbShortPassYAC = "1080";
            request.oShortPassYAC = "1039.39";
            request.dShortPassYAC = "1100";
            request.qbMediumPassYAC = "1100.106";
            request.oMediumPassYAC = "1144.005";
            request.dMediumPassYAC = "1100";
            request.qbLongPassYAC = "1100";
            request.oLongPassYAC = "1158.315";
            request.dLongPassYAC = "1100";
            request.dPassCover = "58.24";
            request.dInterceptor = "1103.474";
            request.rReceiverShort = "1225";
            request.rReceiverMedium = "800";
            request.rReceiverLong = "800";
            request.rReceiverEndzone = "1100";
            request.kFieldGoalBlock = "989.681";
            request.kFieldGoalMake = "1007.622";
            request.kPunt = "1100";
            request.rPunt = "1100";
            request.kPuntReturn = "1099.125";
            request.rPuntReturn = "1100.82";
            request.kKickOffTouchback = "1100";
            request.rKickOffTouchback = "1100";
            request.kKickReturnEfficiency = "1100";
            request.rKickReturnEfficiency = "1100";

            return request;
        }
    }
}
