using ASF.Core.Common.Messages.Enums;
using AutomationFramework.Model.WorkbookWebApi;

namespace AutomationFramework.DefaultRequests
{
    internal static class WorkbookWebApiRequests
    {
        public static NflMarketPublishLinesRequestModel NflFixturePublishLineRequest(string fixtureKey)
        {
            return new NflMarketPublishLinesRequestModel
            {
                FixtureKey = fixtureKey,
                SimulationKey = "Production",
                ClientKey = "Prod",

                MMM = 1,
                MMS = 21,
                MMT = 21,
                MMH = 11,
                MMA = 11,
                H1M = 1,
                H1S = 11,
                H1T = 11,
                H1H = 5,
                H1A = 5,
                H2M = 1,
                H2S = 11,
                H2T = 11,
                H2H = 5,
                H2A = 5,
                Q1M = 1,
                Q1S = 11,
                Q1T = 11,
                Q1H = 5,
                Q1A = 5,
                Q2M = 1,
                Q2S = 11,
                Q2T = 11,
                Q2H = 5,
                Q2A = 5,
                Q3M = 1,
                Q3S = 11,
                Q3T = 11,
                Q3H = 5,
                Q3A = 5,
                Q4M = 1,
                Q4S = 11,
                Q4T = 11,
                Q4H = 5,
                Q4A = 5,
                MMC = 1,
                H1C = 1,
                H2C = 1,
                Q1C = 1,
                Q2C = 1,
                Q3C = 1,
                Q4C = 1,
                FMT = 1,
                LMT = 1,
                NMT = 1,
                FMH = 1,
                LMH = 1,
                NMH = 1,
                FMA = 1,
                LMA = 1,
                NMA = 1,
                TPY = 1,
                TPA = 1,
                TPC = 1,
                TPD = 1,
                TIN = 1,
                TIP = 1,
                TCT = 1,
                TCY = 1,
                TCR = 1,
                TRT = 1,
                TRY = 1,
                TRR = 1,
                TTD = 5,
                TCM = 1,
                TCP = 1,
                TDI = 1,
                TDS = 1,
                TDT = 1,
                TFL = 1,
                MPY = 5,
                MCY = 5,
                MRY = 5,
                MRR = 5,
                XPY = 1,
                XPA = 1,
                XCM = 1,
                XPD = 1,
                XIN = 1,
                XCY = 1,
                XCR = 1,
                XTA = 1,
                XRY = 1,
                XRA = 1,
                XRR = 1,
                XTD = 1,
                XKM = 1,
                HRY = 1,
                HCY = 1,
                SPY = 1,
                SPA = 1,
                SCM = 1,
                SPD = 1,
                SIN = 1,
                SCY = 1,
                SCR = 1,
                STA = 1,
                SRY = 1,
                SRA = 1,
                SRR = 1,
                STD = 1,
                SKM = 1,
                RRY = 1,
                RCY = 1,
                PPY = 1,
                PPA = 1,
                PCM = 1,
                PPD = 1,
                PIN = 1,
                PIP = 1,
                PCT = 1,
                PCY = 1,
                PCR = 1,
                PTA = 1,
                PRT = 1,
                PRY = 1,
                PRA = 1,
                PRR = 1,
                PTD = 1,
                PKM = 1,
                PKP = 1,
                PDI = 1,
                PDS = 1,
                PDT = 1,
                DPR = 1,
                D4C = 1,
                D1G = 1,
                DSK = 1,
                DRZ = 1,
                D50 = 1,
                D30 = 1,
                DIN = 1,
                DLP = 1,
                DNP = 1,
                DN1 = 1,
                DNC = 1,
                DLC = 1,
                DL3 = 1,
                DC3 = 1,
                DOC = 1,
                TSK = 1,
                TDK = 1
            };
        }

        public static MlbMarketPublishLinesRequestModel MlbFixturePublishLineRequest(string fixtureKey)
        {
            return new MlbMarketPublishLinesRequestModel
            {
                FixtureKey = fixtureKey,
                SimulationKey = "Production",

                MM_M = 1,
                MM_T = 15,
                MM_S = 11,
                MM_H = 11,
                MM_A = 11,
                FH_M = 1,
                FH_T = 11,
                FH_S = 5,
                FH_H = 5,
                FH_A = 5,
                BTH = 1,
                BTK = 1,
                BTR = 1,
                BHR = 1,
                BHW = 1,
                BTB = 1,
                BTI = 1,
                BHH = 1,
                PTH = 1,
                PTK = 1,
                PTR = 1,
                PHR = 1,
                PHL = 1,
                PTB = 1,
                PTO = 1,
                PRW = 1,
                BBB = 1,
                BHM = 1,
                BHT = 1,
                BKS = 1,
                BMX = 1,
                BOB = 1,
                BMB = 1,
                PBB = 1,
                PHM = 1,
                PHT = 1,
                PKS = 1,
                PMX = 1,
                POB = 1,
                PMO = 1,
                IAO = 1,
                IBL = 1,
                IBF = 1,
                IDP = 1,
                IGO = 1,
                IHT = 1,
                IHR = 1,
                ILB = 1,
                IPT = 1,
                IRS = 1,
                ISB = 1,
                IKS = 1,
                IBB = 1,
                IXB = 1,
                ABB = -1,
                ABS = -1,
                ADO = -1,
                AEB = -1,
                AHR = -1,
                AKS = -1,
                AOE = -1,
                ARE = -1,
                ARH = -1,
                ASI = -1,
                ATR = -1,
                ATT = -1
            };
        }

        public static FixturePublishRequestModel FixturePublishRequest(string fixtureKey)
        {
            return new FixturePublishRequestModel
            {
                FixtureKey = fixtureKey,
                SimulationKey = "Production",
                ClientKey = "Prod",
                Published = PublishType.Published
            };
        }

        public static FixturePublishRequestModel FixtureUnPublishRequest(string fixtureKey)
        {
            return new FixturePublishRequestModel
            {
                FixtureKey = fixtureKey,
                SimulationKey = "Production",
                ClientKey = "Prod",
                Published = PublishType.Unpublished
            };
        }

        public static UserSimRequestModel UserSimRequest(string fixtureKey, int numberOfSimsRequired = 60000)
        {
            return new UserSimRequestModel
            {
                FixtureKey = fixtureKey,
                SimulationKey = "Production",
                NumberOfSimsRequested = numberOfSimsRequired
            };
        }
    }
}
